/**
 * EdTech Navigator – Shared Tools Database
 *
 * Fields per tool:
 *   id              – unique integer
 *   name            – display name
 *   vendor          – company / creator
 *   website         – canonical URL
 *   category        – top-level category
 *   subcategory     – narrower label
 *   gradeLevels     – grade range string
 *   subjects        – array of subject strings
 *   intendedUsers   – array: "Teachers" | "Students" | "Admins" | "Parents"
 *   platformType    – "Web/Mobile" | "Web" | "Mobile/Web" etc.
 *   pricingModel    – free-text pricing description
 *   parentRelevant  – "High" | "Medium" | "Low"
 *   teacherRelevant – "High" | "Medium" | "Low"
 *   adminRelevant   – "High" | "Medium" | "Low"
 *   description     – short description
 */

const EDTECH_TOOLS = [
  {
    id: 1,
    name: "Google Classroom",
    vendor: "Google",
    website: "https://classroom.google.com",
    category: "Learning Management",
    subcategory: "LMS",
    gradeLevels: "K-12",
    subjects: ["All"],
    intendedUsers: ["Teachers", "Students", "Admins", "Parents"],
    platformType: "Web/Mobile",
    pricingModel: "Free with Google Workspace for Schools",
    parentRelevant: "Medium",
    teacherRelevant: "High",
    adminRelevant: "High",
    description: "Classroom hub for assignments, communication, and organization."
  },
  {
    id: 2,
    name: "Canvas",
    vendor: "Instructure",
    website: "https://www.instructure.com/canvas-k-12",
    category: "Learning Management",
    subcategory: "LMS",
    gradeLevels: "K-12",
    subjects: ["All"],
    intendedUsers: ["Teachers", "Students", "Admins", "Parents"],
    platformType: "Web/Mobile",
    pricingModel: "School/District license; some free tiers",
    parentRelevant: "Medium",
    teacherRelevant: "High",
    adminRelevant: "High",
    description: "K-12 LMS for course delivery, grading, and communication."
  },
  {
    id: 3,
    name: "Schoology Learning",
    vendor: "PowerSchool",
    website: "https://www.powerschool.com/solutions/personalized-learning/schoology-learning/",
    category: "Learning Management",
    subcategory: "LMS",
    gradeLevels: "K-12",
    subjects: ["All"],
    intendedUsers: ["Teachers", "Students", "Admins", "Parents"],
    platformType: "Web/Mobile",
    pricingModel: "School/District license",
    parentRelevant: "Medium",
    teacherRelevant: "High",
    adminRelevant: "High",
    description: "Centralized LMS for personalized teaching and learning."
  },
  {
    id: 4,
    name: "Microsoft Teams for Education",
    vendor: "Microsoft",
    website: "https://www.microsoft.com/en-us/microsoft-365/microsoft-teams/education/ms",
    category: "Learning Management",
    subcategory: "Communication",
    gradeLevels: "K-12",
    subjects: ["All"],
    intendedUsers: ["Teachers", "Students", "Admins", "Parents"],
    platformType: "Web/Mobile",
    pricingModel: "Free with eligible school account",
    parentRelevant: "Medium",
    teacherRelevant: "High",
    adminRelevant: "High",
    description: "Collaboration, chat, assignments, class materials, and meetings."
  },
  {
    id: 5,
    name: "Moodle",
    vendor: "Moodle",
    website: "https://moodle.org",
    category: "Learning Management",
    subcategory: "LMS",
    gradeLevels: "K-12",
    subjects: ["All"],
    intendedUsers: ["Teachers", "Students"],
    platformType: "Web/Mobile",
    pricingModel: "Open source / Free",
    parentRelevant: "Low",
    teacherRelevant: "High",
    adminRelevant: "High",
    description: "Open-source LMS used for course management and online learning."
  },
  {
    id: 6,
    name: "Blackboard Learn",
    vendor: "Anthology",
    website: "https://www.anthology.com/products/teaching-and-learning/learning-effectiveness/blackboard",
    category: "Learning Management",
    subcategory: "LMS",
    gradeLevels: "K-12",
    subjects: ["All"],
    intendedUsers: ["Teachers", "Students", "Admins"],
    platformType: "Web/Mobile",
    pricingModel: "Institutional license",
    parentRelevant: "Low",
    teacherRelevant: "Medium",
    adminRelevant: "High",
    description: "Enterprise LMS used for course delivery and assessment."
  },
  {
    id: 7,
    name: "Brightspace",
    vendor: "D2L",
    website: "https://www.d2l.com/brightspace/k-12/",
    category: "Learning Management",
    subcategory: "LMS",
    gradeLevels: "K-12",
    subjects: ["All"],
    intendedUsers: ["Teachers", "Students", "Admins", "Parents"],
    platformType: "Web/Mobile",
    pricingModel: "School/District license",
    parentRelevant: "Medium",
    teacherRelevant: "High",
    adminRelevant: "High",
    description: "Cloud LMS supporting instruction, assessment, and analytics."
  },
  {
    id: 8,
    name: "itslearning",
    vendor: "itslearning",
    website: "https://itslearning.com/us/",
    category: "Learning Management",
    subcategory: "LMS",
    gradeLevels: "K-12",
    subjects: ["All"],
    intendedUsers: ["Teachers", "Students", "Admins", "Parents"],
    platformType: "Web/Mobile",
    pricingModel: "School/District license",
    parentRelevant: "Medium",
    teacherRelevant: "High",
    adminRelevant: "High",
    description: "LMS for lessons, planning, assignments, and communication."
  },
  {
    id: 9,
    name: "Otus",
    vendor: "Otus",
    website: "https://otus.com",
    category: "Learning Management",
    subcategory: "Assessment+",
    gradeLevels: "K-12",
    subjects: ["All"],
    intendedUsers: ["Teachers", "Students", "Admins", "Parents"],
    platformType: "Web/Mobile",
    pricingModel: "School/District license",
    parentRelevant: "Medium",
    teacherRelevant: "High",
    adminRelevant: "High",
    description: "Platform combining assessment, data, and classroom workflows."
  },
  {
    id: 10,
    name: "Toddle",
    vendor: "Toddle",
    website: "https://www.toddleapp.com",
    category: "Learning Management",
    subcategory: "Curriculum+",
    gradeLevels: "K-12",
    subjects: ["All"],
    intendedUsers: ["Teachers", "Students", "Admins", "Parents"],
    platformType: "Web/Mobile",
    pricingModel: "School/District license",
    parentRelevant: "Low",
    teacherRelevant: "High",
    adminRelevant: "High",
    description: "Teaching and learning platform with curriculum, portfolios, and communication."
  },
  {
    id: 11,
    name: "Clever",
    vendor: "Clever",
    website: "https://www.clever.com",
    category: "Access & Identity Management",
    subcategory: "SSO Portal",
    gradeLevels: "K-12",
    subjects: ["All"],
    intendedUsers: ["Students", "Teachers", "Admins"],
    platformType: "Web/Mobile",
    pricingModel: "School/District license",
    parentRelevant: "Low",
    teacherRelevant: "High",
    adminRelevant: "High",
    description: "Secure single sign-on and app portal for digital learning."
  },
  {
    id: 12,
    name: "ClassLink",
    vendor: "ClassLink",
    website: "https://www.classlink.com",
    category: "Access & Identity Management",
    subcategory: "SSO Portal",
    gradeLevels: "K-12",
    subjects: ["All"],
    intendedUsers: ["Students", "Teachers", "Admins"],
    platformType: "Web/Mobile",
    pricingModel: "School/District license",
    parentRelevant: "Low",
    teacherRelevant: "High",
    adminRelevant: "High",
    description: "Single sign-on and identity/access management for schools."
  },
  {
    id: 13,
    name: "Google Workspace for Education",
    vendor: "Google",
    website: "https://edu.google.com/workspace-for-education/",
    category: "Productivity & Suite",
    subcategory: "Suite",
    gradeLevels: "K-12",
    subjects: ["All"],
    intendedUsers: ["Teachers", "Students", "Admins"],
    platformType: "Web/Mobile",
    pricingModel: "Free and paid editions",
    parentRelevant: "Low",
    teacherRelevant: "High",
    adminRelevant: "High",
    description: "Productivity suite including Docs, Drive, Meet, and Classroom integration."
  },
  {
    id: 14,
    name: "Microsoft 365 Education",
    vendor: "Microsoft",
    website: "https://www.microsoft.com/en-us/education/products/microsoft365",
    category: "Productivity & Suite",
    subcategory: "Suite",
    gradeLevels: "K-12",
    subjects: ["All"],
    intendedUsers: ["Teachers", "Students", "Admins"],
    platformType: "Web/Mobile",
    pricingModel: "Free and paid education plans",
    parentRelevant: "Low",
    teacherRelevant: "High",
    adminRelevant: "High",
    description: "Productivity suite with Office apps, Teams, and collaboration tools."
  },
  {
    id: 15,
    name: "Seesaw",
    vendor: "Seesaw",
    website: "https://app.seesaw.me",
    category: "Family Engagement",
    subcategory: "Portfolio + Communication",
    gradeLevels: "PreK-6",
    subjects: ["All"],
    intendedUsers: ["Teachers", "Parents"],
    platformType: "Web/Mobile",
    pricingModel: "Free; district solutions available",
    parentRelevant: "High",
    teacherRelevant: "High",
    adminRelevant: "Medium",
    description: "Student portfolios and family communication platform."
  },
  {
    id: 16,
    name: "ClassDojo",
    vendor: "ClassDojo",
    website: "https://www.classdojo.com",
    category: "Family Engagement",
    subcategory: "Communication",
    gradeLevels: "K-8",
    subjects: ["All"],
    intendedUsers: ["Admins", "Teachers", "Parents"],
    platformType: "Web/Mobile",
    pricingModel: "Free; district solutions available",
    parentRelevant: "High",
    teacherRelevant: "High",
    adminRelevant: "Medium",
    description: "Classroom communication, behavior feedback, and student portfolios."
  },
  {
    id: 17,
    name: "Remind",
    vendor: "Remind",
    website: "https://www.remind.com",
    category: "Family Engagement",
    subcategory: "Messaging",
    gradeLevels: "K-12",
    subjects: ["All"],
    intendedUsers: ["Admins", "Teachers", "Parents"],
    platformType: "Web/Mobile",
    pricingModel: "Free and paid plans",
    parentRelevant: "High",
    teacherRelevant: "High",
    adminRelevant: "High",
    description: "School-home messaging and announcements platform."
  },
  {
    id: 18,
    name: "ParentSquare",
    vendor: "ParentSquare",
    website: "https://www.parentsquare.com",
    category: "Family Engagement",
    subcategory: "School Communications",
    gradeLevels: "K-12",
    subjects: ["All"],
    intendedUsers: ["Admins", "Teachers", "Parents", "Students"],
    platformType: "Web/Mobile",
    pricingModel: "School/District license",
    parentRelevant: "High",
    teacherRelevant: "High",
    adminRelevant: "High",
    description: "Unified school-home communication platform."
  },
  {
    id: 19,
    name: "TalkingPoints",
    vendor: "TalkingPoints",
    website: "https://talkingpts.org",
    category: "Family Engagement",
    subcategory: "Multilingual Communication",
    gradeLevels: "K-12",
    subjects: ["All"],
    intendedUsers: ["Teachers", "Parents", "Admins"],
    platformType: "Web/Mobile",
    pricingModel: "Free and paid plans",
    parentRelevant: "High",
    teacherRelevant: "High",
    adminRelevant: "Low",
    description: "Family communication platform with multilingual translation support."
  },
  {
    id: 20,
    name: "Bloomz",
    vendor: "Bloomz",
    website: "https://www.bloomz.com",
    category: "Family Engagement",
    subcategory: "Communication",
    gradeLevels: "K-8",
    subjects: ["All"],
    intendedUsers: ["Teachers", "Parents", "Admins"],
    platformType: "Web/Mobile",
    pricingModel: "Free and paid plans",
    parentRelevant: "High",
    teacherRelevant: "High",
    adminRelevant: "Low",
    description: "Teacher-family communication and classroom updates."
  },
  {
    id: 21,
    name: "Konstella",
    vendor: "Konstella",
    website: "https://www.konstella.com",
    category: "Family Engagement",
    subcategory: "Parent Communication",
    gradeLevels: "K-12",
    subjects: ["All"],
    intendedUsers: ["Parents", "Admins", "Teachers"],
    platformType: "Web/Mobile",
    pricingModel: "School/organization plans",
    parentRelevant: "High",
    teacherRelevant: "Low",
    adminRelevant: "Medium",
    description: "Parent communication and school community coordination."
  },
  {
    id: 22,
    name: "Peachjar",
    vendor: "Peachjar",
    website: "https://www.peachjar.com",
    category: "Family Engagement",
    subcategory: "Digital Flyers",
    gradeLevels: "K-12",
    subjects: ["All"],
    intendedUsers: ["Admins", "Parents"],
    platformType: "Web/Mobile",
    pricingModel: "Organization pricing",
    parentRelevant: "High",
    teacherRelevant: "Low",
    adminRelevant: "Medium",
    description: "Digital flyer distribution for school communications."
  },
  {
    id: 23,
    name: "Newsela",
    vendor: "Newsela",
    website: "https://newsela.com",
    category: "ELA & Content",
    subcategory: "Informational Texts",
    gradeLevels: "K-12",
    subjects: ["ELA", "Social Studies"],
    intendedUsers: ["Teachers", "Students", "Admins", "Parents"],
    platformType: "Web/Mobile",
    pricingModel: "Free and paid school products",
    parentRelevant: "Medium",
    teacherRelevant: "High",
    adminRelevant: "High",
    description: "Standards-aligned current events content and assessments across subjects."
  },
  {
    id: 24,
    name: "CommonLit",
    vendor: "CommonLit",
    website: "https://www.commonlit.org",
    category: "ELA & Content",
    subcategory: "Reading Platform",
    gradeLevels: "K-12",
    subjects: ["ELA"],
    intendedUsers: ["Teachers", "Parents"],
    platformType: "Web/Mobile",
    pricingModel: "Free; paid school edition",
    parentRelevant: "High",
    teacherRelevant: "High",
    adminRelevant: "Low",
    description: "Reading lessons, assessments, and text sets."
  },
  {
    id: 25,
    name: "ReadWorks",
    vendor: "ReadWorks",
    website: "https://www.readworks.org",
    category: "ELA & Content",
    subcategory: "Reading Comprehension",
    gradeLevels: "K-12",
    subjects: ["ELA"],
    intendedUsers: ["Teachers", "Students", "Parents"],
    platformType: "Web/Mobile",
    pricingModel: "Free",
    parentRelevant: "Medium",
    teacherRelevant: "High",
    adminRelevant: "Low",
    description: "Free reading passages, question sets, and article-a-day resources."
  },
  {
    id: 26,
    name: "BrainPOP",
    vendor: "BrainPOP",
    website: "https://www.brainpop.com/discover",
    category: "Core Instruction",
    subcategory: "Multimedia",
    gradeLevels: "K-8+",
    subjects: ["All"],
    intendedUsers: ["Teachers", "Students", "Parents"],
    platformType: "Web/Mobile",
    pricingModel: "Subscription",
    parentRelevant: "Medium",
    teacherRelevant: "High",
    adminRelevant: "Low",
    description: "Animated standards-aligned learning content across subjects."
  },
  {
    id: 27,
    name: "BrainPOP Jr.",
    vendor: "BrainPOP",
    website: "https://jr.brainpop.com",
    category: "Core Instruction",
    subcategory: "Multimedia",
    gradeLevels: "K-3",
    subjects: ["All"],
    intendedUsers: ["Teachers", "Students", "Parents"],
    platformType: "Web/Mobile",
    pricingModel: "Subscription",
    parentRelevant: "Medium",
    teacherRelevant: "High",
    adminRelevant: "Low",
    description: "Early elementary animated learning resources."
  },
  {
    id: 28,
    name: "Discovery Education",
    vendor: "Discovery Education",
    website: "https://www.discoveryeducation.com",
    category: "Core Instruction",
    subcategory: "Digital Content",
    gradeLevels: "K-12",
    subjects: ["All"],
    intendedUsers: ["Teachers", "Students", "Admins"],
    platformType: "Web/Mobile",
    pricingModel: "School/District license",
    parentRelevant: "Low",
    teacherRelevant: "High",
    adminRelevant: "Low",
    description: "Digital curriculum, multimedia, and instructional resources."
  },
  {
    id: 29,
    name: "PBS LearningMedia",
    vendor: "PBS",
    website: "https://www.pbslearningmedia.org",
    category: "Core Instruction",
    subcategory: "Open Resources",
    gradeLevels: "PreK-12",
    subjects: ["All"],
    intendedUsers: ["Teachers", "Students", "Parents"],
    platformType: "Web/Mobile",
    pricingModel: "Free",
    parentRelevant: "Low",
    teacherRelevant: "High",
    adminRelevant: "Low",
    description: "Free standards-aligned videos and lesson resources."
  },
  {
    id: 30,
    name: "CK-12",
    vendor: "CK-12 Foundation",
    website: "https://www.ck12.org",
    category: "Core Instruction",
    subcategory: "Open Texts + Practice",
    gradeLevels: "K-12",
    subjects: ["Math", "Science"],
    intendedUsers: ["Teachers", "Students", "Parents"],
    platformType: "Web/Mobile",
    pricingModel: "Free",
    parentRelevant: "Low",
    teacherRelevant: "High",
    adminRelevant: "Low",
    description: "Free digital textbooks, simulations, and practice."
  },
  {
    id: 31,
    name: "i-Ready",
    vendor: "Curriculum Associates",
    website: "https://www.curriculumassociates.com/programs/i-ready",
    category: "Assessment & Data",
    subcategory: "Diagnostic + Instruction",
    gradeLevels: "K-8",
    subjects: ["Math", "ELA"],
    intendedUsers: ["Teachers", "Students", "Parents"],
    platformType: "Web/Mobile",
    pricingModel: "School/District license",
    parentRelevant: "Medium",
    teacherRelevant: "High",
    adminRelevant: "High",
    description: "Diagnostic assessment and personalized instruction for math and reading."
  },
  {
    id: 32,
    name: "Renaissance Star Assessments",
    vendor: "Renaissance",
    website: "https://www.renaissance.com",
    category: "Assessment & Data",
    subcategory: "Universal Screening",
    gradeLevels: "K-12",
    subjects: ["Math", "Reading"],
    intendedUsers: ["Teachers", "Students", "Admins", "Parents"],
    platformType: "Web/Mobile",
    pricingModel: "School/District license",
    parentRelevant: "Low",
    teacherRelevant: "High",
    adminRelevant: "High",
    description: "Assessment tools for universal screening and progress monitoring."
  },
  {
    id: 33,
    name: "Accelerated Reader",
    vendor: "Renaissance",
    website: "https://www.renaissance.com/products/accelerated-reader/",
    category: "Learning Practice",
    subcategory: "Independent Reading",
    gradeLevels: "K-12",
    subjects: ["Reading"],
    intendedUsers: ["Teachers", "Students", "Admins", "Parents"],
    platformType: "Web/Mobile",
    pricingModel: "School/District license",
    parentRelevant: "Low",
    teacherRelevant: "High",
    adminRelevant: "Medium",
    description: "Independent reading practice and monitoring program."
  },
  {
    id: 34,
    name: "NWEA MAP Growth",
    vendor: "NWEA",
    website: "https://www.nwea.org/map-growth/",
    category: "Assessment & Data",
    subcategory: "Interim Assessment",
    gradeLevels: "K-12",
    subjects: ["Math", "Reading"],
    intendedUsers: ["Teachers", "Students", "Admins", "Parents"],
    platformType: "Web/Mobile",
    pricingModel: "School/District license",
    parentRelevant: "Low",
    teacherRelevant: "High",
    adminRelevant: "High",
    description: "Adaptive assessment for measuring student growth over time."
  },
  {
    id: 35,
    name: "DIBELS",
    vendor: "Amplify",
    website: "https://amplify.com/programs/amplify-dibels/",
    category: "Assessment & Data",
    subcategory: "Early Literacy",
    gradeLevels: "K-8",
    subjects: ["ELA"],
    intendedUsers: ["Teachers", "Admins"],
    platformType: "Web/Mobile",
    pricingModel: "School/District license",
    parentRelevant: "Low",
    teacherRelevant: "High",
    adminRelevant: "High",
    description: "Literacy screening and progress monitoring for early readers."
  },
  {
    id: 36,
    name: "mCLASS",
    vendor: "Amplify",
    website: "https://amplify.com/programs/amplify-mclass/",
    category: "Assessment & Data",
    subcategory: "Literacy Assessment",
    gradeLevels: "K-6",
    subjects: ["ELA"],
    intendedUsers: ["Teachers", "Admins"],
    platformType: "Web/Mobile",
    pricingModel: "School/District license",
    parentRelevant: "Low",
    teacherRelevant: "High",
    adminRelevant: "High",
    description: "Assessment suite for foundational literacy skills."
  },
  {
    id: 37,
    name: "Lexia Core5",
    vendor: "Lexia",
    website: "https://www.lexialearning.com/core5",
    category: "Reading",
    subcategory: "Foundational Literacy",
    gradeLevels: "PreK-5",
    subjects: ["ELA"],
    intendedUsers: ["Teachers", "Parents"],
    platformType: "Web/Mobile",
    pricingModel: "School/District license",
    parentRelevant: "High",
    teacherRelevant: "High",
    adminRelevant: "High",
    description: "Adaptive literacy instruction for elementary learners."
  },
  {
    id: 38,
    name: "Lexia PowerUp",
    vendor: "Lexia",
    website: "https://www.lexialearning.com/powerup-literacy",
    category: "Reading",
    subcategory: "Adolescent Literacy",
    gradeLevels: "6-12",
    subjects: ["ELA"],
    intendedUsers: ["Teachers", "Students", "Admins"],
    platformType: "Web/Mobile",
    pricingModel: "School/District license",
    parentRelevant: "Low",
    teacherRelevant: "High",
    adminRelevant: "High",
    description: "Literacy support for older and struggling readers."
  },
  {
    id: 39,
    name: "Amira Learning",
    vendor: "Amira Learning",
    website: "https://www.amiralearning.com",
    category: "Reading",
    subcategory: "Oral Reading",
    gradeLevels: "K-6",
    subjects: ["ELA"],
    intendedUsers: ["Teachers", "Students", "Parents"],
    platformType: "Web/Mobile",
    pricingModel: "School/District license",
    parentRelevant: "High",
    teacherRelevant: "High",
    adminRelevant: "High",
    description: "AI-supported reading tutoring and oral reading assessment."
  },
  {
    id: 40,
    name: "Raz-Plus",
    vendor: "Learning A-Z",
    website: "https://www.learninga-z.com/site/products/raz-plus/overview",
    category: "Reading",
    subcategory: "Leveled Reading",
    gradeLevels: "K-6",
    subjects: ["ELA"],
    intendedUsers: ["Teachers", "Students", "Parents"],
    platformType: "Web/Mobile",
    pricingModel: "Subscription",
    parentRelevant: "Medium",
    teacherRelevant: "High",
    adminRelevant: "Low",
    description: "Leveled books and literacy resources for guided reading."
  },
  {
    id: 41,
    name: "Reading A-Z",
    vendor: "Learning A-Z",
    website: "https://www.learninga-z.com/site/products/reading-a-z/overview",
    category: "Reading",
    subcategory: "Leveled Books",
    gradeLevels: "K-6",
    subjects: ["ELA"],
    intendedUsers: ["Teachers", "Students", "Parents"],
    platformType: "Web/Mobile",
    pricingModel: "Subscription",
    parentRelevant: "Medium",
    teacherRelevant: "High",
    adminRelevant: "Low",
    description: "Printable and digital leveled reading resources."
  },
  {
    id: 42,
    name: "Vocabulary.com",
    vendor: "Vocabulary.com",
    website: "https://www.vocabulary.com",
    category: "ELA & Writing",
    subcategory: "Vocabulary",
    gradeLevels: "3-12",
    subjects: ["ELA"],
    intendedUsers: ["Teachers", "Students", "Parents"],
    platformType: "Web/Mobile",
    pricingModel: "Free and paid education plans",
    parentRelevant: "Medium",
    teacherRelevant: "High",
    adminRelevant: "Low",
    description: "Vocabulary practice and adaptive learning for all grades."
  },
  {
    id: 43,
    name: "Epic!",
    vendor: "Epic",
    website: "https://www.getepic.com",
    category: "Reading",
    subcategory: "Digital Library",
    gradeLevels: "PreK-7",
    subjects: ["ELA"],
    intendedUsers: ["Students", "Teachers", "Parents"],
    platformType: "Web/Mobile",
    pricingModel: "Free for educators in class; paid home plan",
    parentRelevant: "High",
    teacherRelevant: "High",
    adminRelevant: "High",
    description: "Digital library of books, audiobooks, and videos for kids."
  },
  {
    id: 44,
    name: "BookNook",
    vendor: "BookNook",
    website: "https://www.booknook.com",
    category: "Reading",
    subcategory: "Tutoring + Intervention",
    gradeLevels: "K-8",
    subjects: ["ELA"],
    intendedUsers: ["Teachers", "Students", "Admins"],
    platformType: "Web/Mobile",
    pricingModel: "School/District license",
    parentRelevant: "Low",
    teacherRelevant: "High",
    adminRelevant: "Low",
    description: "Reading intervention and small-group tutoring platform."
  },
  {
    id: 45,
    name: "Writable",
    vendor: "Houghton Mifflin Harcourt",
    website: "https://www.writable.com",
    category: "ELA & Writing",
    subcategory: "Writing Instruction",
    gradeLevels: "3-12",
    subjects: ["ELA"],
    intendedUsers: ["Teachers", "Students", "Admins", "Parents"],
    platformType: "Web/Mobile",
    pricingModel: "School/District license",
    parentRelevant: "Low",
    teacherRelevant: "High",
    adminRelevant: "Low",
    description: "Writing assignments, feedback, and assessments platform."
  },
  {
    id: 46,
    name: "NoRedInk",
    vendor: "NoRedInk",
    website: "https://www.noredink.com",
    category: "ELA & Writing",
    subcategory: "Grammar + Writing",
    gradeLevels: "5-12",
    subjects: ["ELA"],
    intendedUsers: ["Teachers", "Students", "Admins"],
    platformType: "Web/Mobile",
    pricingModel: "Free and premium",
    parentRelevant: "Medium",
    teacherRelevant: "High",
    adminRelevant: "Low",
    description: "Grammar and writing practice platform."
  },
  {
    id: 47,
    name: "Quill",
    vendor: "Quill.org",
    website: "https://www.quill.org",
    category: "ELA & Writing",
    subcategory: "Grammar + Writing",
    gradeLevels: "3-12",
    subjects: ["ELA"],
    intendedUsers: ["Teachers", "Students", "Admins", "Parents"],
    platformType: "Web/Mobile",
    pricingModel: "Free; premium school tools",
    parentRelevant: "Medium",
    teacherRelevant: "High",
    adminRelevant: "Low",
    description: "Free writing and grammar activities for students."
  },
  {
    id: 48,
    name: "Khan Academy",
    vendor: "Khan Academy",
    website: "https://www.khanacademy.org",
    category: "Core Instruction",
    subcategory: "Practice + Lessons",
    gradeLevels: "K-12",
    subjects: ["All"],
    intendedUsers: ["Teachers", "Students", "Admins", "Parents"],
    platformType: "Web/Mobile",
    pricingModel: "Free",
    parentRelevant: "High",
    teacherRelevant: "High",
    adminRelevant: "Medium",
    description: "Free lessons and practice across all subjects, K-12 and beyond."
  },
  {
    id: 49,
    name: "Khan Academy Kids",
    vendor: "Khan Academy",
    website: "https://www.khanacademy.org/khan-for-educators/khan-kids-page",
    category: "Early Learning",
    subcategory: "Early Learning App",
    gradeLevels: "PreK-2",
    subjects: ["ELA", "Math", "SEL"],
    intendedUsers: ["Students", "Parents", "Teachers"],
    platformType: "Mobile/Web",
    pricingModel: "Free",
    parentRelevant: "High",
    teacherRelevant: "High",
    adminRelevant: "Low",
    description: "Free early learning app with reading, math, and SEL for young children."
  },
  {
    id: 50,
    name: "IXL",
    vendor: "IXL Learning",
    website: "https://www.ixl.com",
    category: "Math & Core Practice",
    subcategory: "Adaptive Practice",
    gradeLevels: "PreK-12",
    subjects: ["Math", "ELA", "Science"],
    intendedUsers: ["Students", "Teachers", "Admins", "Parents"],
    platformType: "Web/Mobile",
    pricingModel: "Subscription / school plans",
    parentRelevant: "Medium",
    teacherRelevant: "High",
    adminRelevant: "Medium",
    description: "Comprehensive adaptive practice and diagnostics across subjects."
  },
  {
    id: 51,
    name: "DreamBox Math",
    vendor: "DreamBox by Curriculum Associates",
    website: "https://www.dreambox.com",
    category: "Math",
    subcategory: "Adaptive Math",
    gradeLevels: "K-8",
    subjects: ["Math"],
    intendedUsers: ["Teachers", "Students", "Admins", "Parents"],
    platformType: "Web/Mobile",
    pricingModel: "Subscription",
    parentRelevant: "Medium",
    teacherRelevant: "High",
    adminRelevant: "Low",
    description: "Adaptive math program with embedded formative assessment."
  },
  {
    id: 52,
    name: "Zearn Math",
    vendor: "Zearn",
    website: "https://www.zearn.org",
    category: "Math",
    subcategory: "Core Math",
    gradeLevels: "K-8",
    subjects: ["Math"],
    intendedUsers: ["Students", "Teachers", "Admins"],
    platformType: "Web/Mobile",
    pricingModel: "Free core access; school offerings available",
    parentRelevant: "High",
    teacherRelevant: "High",
    adminRelevant: "High",
    description: "Visual, teacher-designed digital math lessons."
  },
  {
    id: 53,
    name: "Desmos",
    vendor: "Desmos Studio",
    website: "https://www.desmos.com",
    category: "Math",
    subcategory: "Calculators + Activities",
    gradeLevels: "K-12",
    subjects: ["Math"],
    intendedUsers: ["Students", "Teachers", "Parents"],
    platformType: "Web/Mobile",
    pricingModel: "Free",
    parentRelevant: "Medium",
    teacherRelevant: "High",
    adminRelevant: "Low",
    description: "Free graphing calculator and interactive math activities."
  },
  {
    id: 54,
    name: "Amplify Classroom",
    vendor: "Amplify",
    website: "https://amplify.com/amplify-classroom/",
    category: "Math",
    subcategory: "Interactive Math Activities",
    gradeLevels: "K-12",
    subjects: ["Math"],
    intendedUsers: ["Teachers", "Students"],
    platformType: "Web",
    pricingModel: "Free and paid depending on product",
    parentRelevant: "Low",
    teacherRelevant: "High",
    adminRelevant: "Low",
    description: "Interactive classroom math activities (formerly Desmos Classroom)."
  }
];

/**
 * Returns tools relevant to a given audience, sorted High → Medium → Low.
 * @param {"Teachers"|"Parents"|"Admins"} audience
 * @returns {Array}
 */
function getToolsForAudience(audience) {
  const relevanceKey = {
    Teachers: "teacherRelevant",
    Parents:  "parentRelevant",
    Admins:   "adminRelevant"
  }[audience];

  const order = { High: 0, Medium: 1, Low: 2 };

  return EDTECH_TOOLS
    .filter(t => order[t[relevanceKey]] <= 1) // High or Medium
    .sort((a, b) => order[a[relevanceKey]] - order[b[relevanceKey]]);
}

/**
 * Filters a tool list by a search query (name, category, subject, grade, vendor).
 * @param {Array}  tools
 * @param {string} query
 * @returns {Array}
 */
function filterTools(tools, query) {
  if (!query || !query.trim()) return tools;
  const q = query.toLowerCase();
  return tools.filter(t =>
    t.name.toLowerCase().includes(q) ||
    t.vendor.toLowerCase().includes(q) ||
    t.category.toLowerCase().includes(q) ||
    t.subcategory.toLowerCase().includes(q) ||
    t.gradeLevels.toLowerCase().includes(q) ||
    t.subjects.some(s => s.toLowerCase().includes(q)) ||
    t.description.toLowerCase().includes(q)
  );
}
