/**
 * EdTech Navigator – Shared Tools Database
 *
 * Fields per tool:
 *   id              – unique integer
 *   name            – display name
 *   vendor          – company / creator
 *   website         – canonical URL
 *   toolType        – e.g. "Program" | "Website/App" | "LMS" | "App" | "Platform"
 *   category        – top-level category
 *   subcategory     – narrower label
 *   gradeLevels     – grade range string
 *   subjects        – array of subject strings
 *   intendedUsers   – array: "Teachers" | "Students" | "Admins" | "Parents"
 *   platforms       – comma-separated platform string
 *   pricingModel    – free-text pricing description
 *   rating          – integer 4 or 5 (★★★★☆ or ★★★★★)
 *   parentRelevant  – "High" | "Medium" | "Low"
 *   teacherRelevant – "High" | "Medium" | "Low"
 *   adminRelevant   – "High" | "Medium" | "Low"
 *   description     – short description
 */

const EDTECH_TOOLS = [

  // ── CLASSROOM MANAGEMENT & LMS ────────────────────────────────
  {
    id: 1,
    name: "Google Classroom",
    vendor: "Google",
    website: "https://classroom.google.com",
    toolType: "Platform",
    category: "Classroom Management & LMS",
    subcategory: "LMS",
    gradeLevels: "K-12",
    subjects: ["All"],
    intendedUsers: ["Teachers", "Students", "Admins", "Parents"],
    platforms: "Web, iOS, Android",
    pricingModel: "Free (Google Workspace for Education)",
    rating: 5,
    parentRelevant: "Medium",
    teacherRelevant: "High",
    adminRelevant: "High",
    description: "Classroom hub for assignments, communication, and organization."
  },
  {
    id: 2,
    name: "Canvas",
    vendor: "Instructure",
    website: "https://www.instructure.com/canvas-k-12",
    toolType: "LMS",
    category: "Classroom Management & LMS",
    subcategory: "LMS",
    gradeLevels: "K-12",
    subjects: ["All"],
    intendedUsers: ["Teachers", "Students", "Admins", "Parents"],
    platforms: "Web, iOS, Android",
    pricingModel: "Free K-12 version; paid enterprise",
    rating: 5,
    parentRelevant: "Medium",
    teacherRelevant: "High",
    adminRelevant: "High",
    description: "K-12 LMS for course delivery, grading, and communication."
  },
  {
    id: 3,
    name: "Schoology",
    vendor: "PowerSchool",
    website: "https://www.powerschool.com/solutions/personalized-learning/schoology-learning/",
    toolType: "LMS",
    category: "Classroom Management & LMS",
    subcategory: "LMS",
    gradeLevels: "K-12",
    subjects: ["All"],
    intendedUsers: ["Teachers", "Students", "Admins", "Parents"],
    platforms: "Web, iOS, Android",
    pricingModel: "Free basic; PowerSchool Enterprise pricing",
    rating: 4,
    parentRelevant: "Medium",
    teacherRelevant: "High",
    adminRelevant: "High",
    description: "Centralized LMS for personalized teaching and learning."
  },
  {
    id: 4,
    name: "Microsoft Teams for Education",
    vendor: "Microsoft",
    website: "https://www.microsoft.com/en-us/microsoft-365/microsoft-teams/education/ms",
    toolType: "Platform",
    category: "Classroom Management & LMS",
    subcategory: "Communication",
    gradeLevels: "K-12",
    subjects: ["All"],
    intendedUsers: ["Teachers", "Students", "Admins", "Parents"],
    platforms: "Web, iOS, Android, Windows",
    pricingModel: "Free with eligible school account",
    rating: 4,
    parentRelevant: "Medium",
    teacherRelevant: "High",
    adminRelevant: "High",
    description: "Collaboration, chat, assignments, class materials, and meetings."
  },
  {
    id: 15,
    name: "Seesaw",
    vendor: "Seesaw",
    website: "https://app.seesaw.me",
    toolType: "App/Web",
    category: "Classroom Management & LMS",
    subcategory: "Portfolio + Communication",
    gradeLevels: "PreK-8",
    subjects: ["All"],
    intendedUsers: ["Teachers", "Students", "Parents"],
    platforms: "Web, iOS, Android",
    pricingModel: "Free; Plus ~$120/teacher",
    rating: 5,
    parentRelevant: "High",
    teacherRelevant: "High",
    adminRelevant: "Medium",
    description: "Student portfolios and family communication platform for PreK–8."
  },
  {
    id: 16,
    name: "ClassDojo",
    vendor: "ClassDojo",
    website: "https://www.classdojo.com",
    toolType: "App/Web",
    category: "Classroom Management & LMS",
    subcategory: "Behavior & Communication",
    gradeLevels: "K-8",
    subjects: ["All"],
    intendedUsers: ["Teachers", "Students", "Admins", "Parents"],
    platforms: "Web, iOS, Android",
    pricingModel: "Free; Plus ~$7.99/mo families",
    rating: 5,
    parentRelevant: "High",
    teacherRelevant: "High",
    adminRelevant: "Medium",
    description: "Classroom communication, behavior feedback, and student portfolios."
  },
  {
    id: 17,
    name: "Remind",
    vendor: "Remind",
    website: "https://www.remind.com",
    toolType: "App",
    category: "Classroom Management & LMS",
    subcategory: "Messaging",
    gradeLevels: "K-12",
    subjects: ["All"],
    intendedUsers: ["Admins", "Teachers", "Parents"],
    platforms: "iOS, Android, Web",
    pricingModel: "Free; Hub premium",
    rating: 4,
    parentRelevant: "High",
    teacherRelevant: "High",
    adminRelevant: "High",
    description: "School-home messaging and announcements platform."
  },
  {
    id: 5,
    name: "Moodle",
    vendor: "Moodle",
    website: "https://moodle.org",
    toolType: "LMS",
    category: "Classroom Management & LMS",
    subcategory: "LMS",
    gradeLevels: "K-12",
    subjects: ["All"],
    intendedUsers: ["Teachers", "Students"],
    platforms: "Web",
    pricingModel: "Open source / Free",
    rating: 4,
    parentRelevant: "Low",
    teacherRelevant: "High",
    adminRelevant: "High",
    description: "Open-source LMS used for course management and online learning."
  },
  {
    id: 6,
    name: "Blackboard Learn",
    vendor: "Anthology",
    website: "https://www.anthology.com/products/teaching-and-learning/learning-effectiveness/blackboard",
    toolType: "LMS",
    category: "Classroom Management & LMS",
    subcategory: "LMS",
    gradeLevels: "K-12",
    subjects: ["All"],
    intendedUsers: ["Teachers", "Students", "Admins"],
    platforms: "Web, iOS, Android",
    pricingModel: "Institutional license",
    rating: 4,
    parentRelevant: "Low",
    teacherRelevant: "Medium",
    adminRelevant: "High",
    description: "Enterprise LMS used for course delivery and assessment."
  },
  {
    id: 7,
    name: "Brightspace",
    vendor: "D2L",
    website: "https://www.d2l.com/brightspace/k-12/",
    toolType: "LMS",
    category: "Classroom Management & LMS",
    subcategory: "LMS",
    gradeLevels: "K-12",
    subjects: ["All"],
    intendedUsers: ["Teachers", "Students", "Admins", "Parents"],
    platforms: "Web, iOS, Android",
    pricingModel: "School/District license",
    rating: 4,
    parentRelevant: "Medium",
    teacherRelevant: "High",
    adminRelevant: "High",
    description: "Cloud LMS supporting instruction, assessment, and analytics."
  },
  {
    id: 8,
    name: "itslearning",
    vendor: "itslearning",
    website: "https://itslearning.com/us/",
    toolType: "LMS",
    category: "Classroom Management & LMS",
    subcategory: "LMS",
    gradeLevels: "K-12",
    subjects: ["All"],
    intendedUsers: ["Teachers", "Students", "Admins", "Parents"],
    platforms: "Web, iOS, Android",
    pricingModel: "School/District license",
    rating: 4,
    parentRelevant: "Medium",
    teacherRelevant: "High",
    adminRelevant: "High",
    description: "LMS for lessons, planning, assignments, and communication."
  },
  {
    id: 9,
    name: "Otus",
    vendor: "Otus",
    website: "https://otus.com",
    toolType: "Platform",
    category: "Classroom Management & LMS",
    subcategory: "Assessment + LMS",
    gradeLevels: "K-12",
    subjects: ["All"],
    intendedUsers: ["Teachers", "Students", "Admins", "Parents"],
    platforms: "Web, iOS, Android",
    pricingModel: "School/District license",
    rating: 4,
    parentRelevant: "Medium",
    teacherRelevant: "High",
    adminRelevant: "High",
    description: "Platform combining assessment, data, and classroom workflows."
  },
  {
    id: 10,
    name: "Toddle",
    vendor: "Toddle",
    website: "https://www.toddleapp.com",
    toolType: "Platform",
    category: "Classroom Management & LMS",
    subcategory: "Curriculum + Portfolio",
    gradeLevels: "K-12",
    subjects: ["All"],
    intendedUsers: ["Teachers", "Students", "Admins", "Parents"],
    platforms: "Web, iOS, Android",
    pricingModel: "School/District license",
    rating: 4,
    parentRelevant: "Low",
    teacherRelevant: "High",
    adminRelevant: "High",
    description: "Teaching and learning platform with curriculum, portfolios, and communication."
  },

  // ── ACCESS & PRODUCTIVITY ─────────────────────────────────────
  {
    id: 11,
    name: "Clever",
    vendor: "Clever",
    website: "https://www.clever.com",
    toolType: "Platform",
    category: "Access & Identity Management",
    subcategory: "SSO Portal",
    gradeLevels: "K-12",
    subjects: ["All"],
    intendedUsers: ["Students", "Teachers", "Admins"],
    platforms: "Web",
    pricingModel: "School/District license",
    rating: 4,
    parentRelevant: "Low",
    teacherRelevant: "High",
    adminRelevant: "High",
    description: "Secure single sign-on and app portal for digital learning."
  },
  {
    id: 12,
    name: "ClassLink",
    vendor: "ClassLink",
    website: "https://www.classlink.com",
    toolType: "Platform",
    category: "Access & Identity Management",
    subcategory: "SSO Portal",
    gradeLevels: "K-12",
    subjects: ["All"],
    intendedUsers: ["Students", "Teachers", "Admins"],
    platforms: "Web, iOS, Android",
    pricingModel: "School/District license",
    rating: 4,
    parentRelevant: "Low",
    teacherRelevant: "High",
    adminRelevant: "High",
    description: "Single sign-on and identity/access management for schools."
  },
  {
    id: 13,
    name: "Google Workspace for Education",
    vendor: "Google",
    website: "https://edu.google.com/workspace-for-education/",
    toolType: "Suite",
    category: "Productivity & Suite",
    subcategory: "Suite",
    gradeLevels: "K-12",
    subjects: ["All"],
    intendedUsers: ["Teachers", "Students", "Admins"],
    platforms: "Web, iOS, Android",
    pricingModel: "Free and paid editions",
    rating: 5,
    parentRelevant: "Low",
    teacherRelevant: "High",
    adminRelevant: "High",
    description: "Productivity suite including Docs, Drive, Meet, and Classroom integration."
  },
  {
    id: 14,
    name: "Microsoft 365 Education",
    vendor: "Microsoft",
    website: "https://www.microsoft.com/en-us/education/products/microsoft365",
    toolType: "Suite",
    category: "Productivity & Suite",
    subcategory: "Suite",
    gradeLevels: "K-12",
    subjects: ["All"],
    intendedUsers: ["Teachers", "Students", "Admins"],
    platforms: "Web, iOS, Android, Windows",
    pricingModel: "Free and paid education plans",
    rating: 4,
    parentRelevant: "Low",
    teacherRelevant: "High",
    adminRelevant: "High",
    description: "Productivity suite with Office apps, Teams, and collaboration tools."
  },

  // ── FAMILY ENGAGEMENT ─────────────────────────────────────────
  {
    id: 18,
    name: "ParentSquare",
    vendor: "ParentSquare",
    website: "https://www.parentsquare.com",
    toolType: "Platform",
    category: "Family Engagement",
    subcategory: "School Communications",
    gradeLevels: "K-12",
    subjects: ["All"],
    intendedUsers: ["Admins", "Teachers", "Parents", "Students"],
    platforms: "Web, iOS, Android",
    pricingModel: "School/District license",
    rating: 4,
    parentRelevant: "High",
    teacherRelevant: "High",
    adminRelevant: "High",
    description: "Unified school-home communication platform."
  },
  {
    id: 19,
    name: "TalkingPoints",
    vendor: "TalkingPoints",
    website: "https://talkingpts.org",
    toolType: "App/Web",
    category: "Family Engagement",
    subcategory: "Multilingual Communication",
    gradeLevels: "K-12",
    subjects: ["All"],
    intendedUsers: ["Teachers", "Parents", "Admins"],
    platforms: "Web, iOS, Android",
    pricingModel: "Free and paid plans",
    rating: 4,
    parentRelevant: "High",
    teacherRelevant: "High",
    adminRelevant: "Low",
    description: "Family communication platform with multilingual translation support."
  },
  {
    id: 20,
    name: "Bloomz",
    vendor: "Bloomz",
    website: "https://www.bloomz.com",
    toolType: "App/Web",
    category: "Family Engagement",
    subcategory: "Communication",
    gradeLevels: "K-8",
    subjects: ["All"],
    intendedUsers: ["Teachers", "Parents", "Admins"],
    platforms: "Web, iOS, Android",
    pricingModel: "Free and paid plans",
    rating: 4,
    parentRelevant: "High",
    teacherRelevant: "High",
    adminRelevant: "Low",
    description: "Teacher-family communication and classroom updates."
  },
  {
    id: 21,
    name: "Konstella",
    vendor: "Konstella",
    website: "https://www.konstella.com",
    toolType: "App/Web",
    category: "Family Engagement",
    subcategory: "Parent Communication",
    gradeLevels: "K-12",
    subjects: ["All"],
    intendedUsers: ["Parents", "Admins", "Teachers"],
    platforms: "Web, iOS, Android",
    pricingModel: "School/organization plans",
    rating: 4,
    parentRelevant: "High",
    teacherRelevant: "Low",
    adminRelevant: "Medium",
    description: "Parent communication and school community coordination."
  },
  {
    id: 22,
    name: "Peachjar",
    vendor: "Peachjar",
    website: "https://www.peachjar.com",
    toolType: "Website",
    category: "Family Engagement",
    subcategory: "Digital Flyers",
    gradeLevels: "K-12",
    subjects: ["All"],
    intendedUsers: ["Admins", "Parents"],
    platforms: "Web",
    pricingModel: "Organization pricing",
    rating: 4,
    parentRelevant: "High",
    teacherRelevant: "Low",
    adminRelevant: "Medium",
    description: "Digital flyer distribution for school communications."
  },

  // ── READING & LITERACY ────────────────────────────────────────
  {
    id: 37,
    name: "Lexia Core5",
    vendor: "Lexia",
    website: "https://www.lexialearning.com/core5",
    toolType: "Program",
    category: "Reading & Literacy",
    subcategory: "Foundational Literacy",
    gradeLevels: "PreK-5",
    subjects: ["ELA"],
    intendedUsers: ["Teachers", "Students", "Parents"],
    platforms: "Web, iPad, Chromebook",
    pricingModel: "Free trial; district licensing",
    rating: 5,
    parentRelevant: "High",
    teacherRelevant: "High",
    adminRelevant: "High",
    description: "Adaptive, research-backed foundational literacy program for PreK–5."
  },
  {
    id: 23,
    name: "Newsela",
    vendor: "Newsela",
    website: "https://newsela.com",
    toolType: "Website/App",
    category: "Reading & Literacy",
    subcategory: "Informational Texts",
    gradeLevels: "2-12",
    subjects: ["ELA", "Social Studies"],
    intendedUsers: ["Teachers", "Students", "Admins", "Parents"],
    platforms: "Web, iOS, Android, Chromebook",
    pricingModel: "Free basic; Pro ~$15/student/yr",
    rating: 4,
    parentRelevant: "Medium",
    teacherRelevant: "High",
    adminRelevant: "High",
    description: "Standards-aligned current events and informational texts with adjustable reading levels."
  },
  {
    id: 41,
    name: "Reading A-Z",
    vendor: "Learning A-Z",
    website: "https://www.learninga-z.com/site/products/reading-a-z/overview",
    toolType: "Website",
    category: "Reading & Literacy",
    subcategory: "Leveled Books",
    gradeLevels: "PreK-6",
    subjects: ["ELA"],
    intendedUsers: ["Teachers", "Students", "Parents"],
    platforms: "Web",
    pricingModel: "$109/teacher/yr",
    rating: 4,
    parentRelevant: "Medium",
    teacherRelevant: "High",
    adminRelevant: "Low",
    description: "Printable and digital leveled reading resources for PreK–6."
  },
  {
    id: 43,
    name: "Epic!",
    vendor: "Epic",
    website: "https://www.getepic.com",
    toolType: "App/Website",
    category: "Reading & Literacy",
    subcategory: "Digital Library",
    gradeLevels: "PreK-6",
    subjects: ["ELA"],
    intendedUsers: ["Students", "Teachers", "Parents"],
    platforms: "Web, iOS, Android",
    pricingModel: "Free for educators; $9.99/mo families",
    rating: 5,
    parentRelevant: "High",
    teacherRelevant: "High",
    adminRelevant: "High",
    description: "Digital library of books, audiobooks, and educational videos for kids."
  },
  {
    id: 40,
    name: "Raz-Plus",
    vendor: "Learning A-Z",
    website: "https://www.learninga-z.com/site/products/raz-plus/overview",
    toolType: "Website/App",
    category: "Reading & Literacy",
    subcategory: "Leveled Reading Bundle",
    gradeLevels: "PreK-6",
    subjects: ["ELA"],
    intendedUsers: ["Teachers", "Students", "Parents"],
    platforms: "Web, iOS, Android",
    pricingModel: "Subscription (school/district)",
    rating: 4,
    parentRelevant: "Medium",
    teacherRelevant: "High",
    adminRelevant: "Low",
    description: "Premium bundle of Learning A-Z reading and writing resources."
  },
  {
    id: 55,
    name: "Raz-Kids",
    vendor: "Learning A-Z",
    website: "https://www.raz-kids.com",
    toolType: "Website/App",
    category: "Reading & Literacy",
    subcategory: "Leveled Reading App",
    gradeLevels: "PreK-5",
    subjects: ["ELA"],
    intendedUsers: ["Teachers", "Students", "Parents"],
    platforms: "Web, iOS, Android",
    pricingModel: "$115/teacher/yr",
    rating: 4,
    parentRelevant: "High",
    teacherRelevant: "High",
    adminRelevant: "Low",
    description: "Digital leveled reading app with built-in audio support and reading quizzes."
  },
  {
    id: 56,
    name: "Sora",
    vendor: "OverDrive",
    website: "https://soraapp.com",
    toolType: "App",
    category: "Reading & Literacy",
    subcategory: "School Library App",
    gradeLevels: "K-12",
    subjects: ["ELA"],
    intendedUsers: ["Students", "Teachers", "Parents"],
    platforms: "iOS, Android, Web",
    pricingModel: "Free via school/library",
    rating: 4,
    parentRelevant: "High",
    teacherRelevant: "Medium",
    adminRelevant: "Medium",
    description: "Borrow school-licensed ebooks and audiobooks through your district's digital library."
  },
  {
    id: 38,
    name: "Lexia PowerUp",
    vendor: "Lexia",
    website: "https://www.lexialearning.com/powerup-literacy",
    toolType: "Program",
    category: "Reading & Literacy",
    subcategory: "Adolescent Literacy",
    gradeLevels: "6-12",
    subjects: ["ELA"],
    intendedUsers: ["Teachers", "Students", "Admins"],
    platforms: "Web, iOS, Android",
    pricingModel: "School/District license",
    rating: 4,
    parentRelevant: "Low",
    teacherRelevant: "High",
    adminRelevant: "High",
    description: "Literacy support program for older and struggling readers in grades 6–12."
  },
  {
    id: 39,
    name: "Amira Learning",
    vendor: "Amira Learning",
    website: "https://www.amiralearning.com",
    toolType: "App/Web",
    category: "Reading & Literacy",
    subcategory: "Oral Reading",
    gradeLevels: "K-6",
    subjects: ["ELA"],
    intendedUsers: ["Teachers", "Students", "Parents"],
    platforms: "Web, iOS, Android",
    pricingModel: "School/District license",
    rating: 4,
    parentRelevant: "High",
    teacherRelevant: "High",
    adminRelevant: "High",
    description: "AI-powered reading tutor that listens to students read aloud and provides real-time coaching."
  },
  {
    id: 44,
    name: "BookNook",
    vendor: "BookNook",
    website: "https://www.booknook.com",
    toolType: "Website",
    category: "Reading & Literacy",
    subcategory: "Tutoring + Intervention",
    gradeLevels: "K-8",
    subjects: ["ELA"],
    intendedUsers: ["Teachers", "Students", "Admins"],
    platforms: "Web",
    pricingModel: "School/District license",
    rating: 4,
    parentRelevant: "Low",
    teacherRelevant: "High",
    adminRelevant: "Low",
    description: "Reading intervention and small-group tutoring platform."
  },
  {
    id: 33,
    name: "Accelerated Reader",
    vendor: "Renaissance",
    website: "https://www.renaissance.com/products/accelerated-reader/",
    toolType: "Program",
    category: "Reading & Literacy",
    subcategory: "Independent Reading",
    gradeLevels: "K-12",
    subjects: ["Reading"],
    intendedUsers: ["Teachers", "Students", "Admins", "Parents"],
    platforms: "Web, iOS, Android",
    pricingModel: "School/District license",
    rating: 4,
    parentRelevant: "Low",
    teacherRelevant: "High",
    adminRelevant: "Medium",
    description: "Independent reading practice and comprehension monitoring program."
  },
  {
    id: 25,
    name: "ReadWorks",
    vendor: "ReadWorks",
    website: "https://www.readworks.org",
    toolType: "Website",
    category: "Reading & Literacy",
    subcategory: "Reading Comprehension",
    gradeLevels: "K-12",
    subjects: ["ELA"],
    intendedUsers: ["Teachers", "Students", "Parents"],
    platforms: "Web",
    pricingModel: "Free",
    rating: 4,
    parentRelevant: "Medium",
    teacherRelevant: "High",
    adminRelevant: "Low",
    description: "Free reading passages, question sets, and article-a-day resources."
  },

  // ── ELA & WRITING ─────────────────────────────────────────────
  {
    id: 24,
    name: "CommonLit",
    vendor: "CommonLit",
    website: "https://www.commonlit.org",
    toolType: "Website",
    category: "ELA & Writing",
    subcategory: "Reading Platform",
    gradeLevels: "3-12",
    subjects: ["ELA"],
    intendedUsers: ["Teachers", "Students", "Parents"],
    platforms: "Web",
    pricingModel: "Free; Plus ~$2,500/school",
    rating: 4,
    parentRelevant: "High",
    teacherRelevant: "High",
    adminRelevant: "Low",
    description: "Free reading lessons, literary texts, assessments, and discussion guides."
  },
  {
    id: 47,
    name: "Quill",
    vendor: "Quill.org",
    website: "https://www.quill.org",
    toolType: "Website",
    category: "ELA & Writing",
    subcategory: "Grammar + Writing",
    gradeLevels: "2-12",
    subjects: ["ELA"],
    intendedUsers: ["Teachers", "Students", "Admins", "Parents"],
    platforms: "Web",
    pricingModel: "Free; Premium ~$80/teacher",
    rating: 4,
    parentRelevant: "Medium",
    teacherRelevant: "High",
    adminRelevant: "Low",
    description: "Free writing and grammar activities that give students instant feedback."
  },
  {
    id: 46,
    name: "NoRedInk",
    vendor: "NoRedInk",
    website: "https://www.noredink.com",
    toolType: "Website",
    category: "ELA & Writing",
    subcategory: "Grammar + Writing",
    gradeLevels: "3-12",
    subjects: ["ELA"],
    intendedUsers: ["Teachers", "Students", "Admins"],
    platforms: "Web",
    pricingModel: "Free; Premium district pricing",
    rating: 5,
    parentRelevant: "Medium",
    teacherRelevant: "High",
    adminRelevant: "Low",
    description: "Adaptive grammar and writing practice using student interests to personalize exercises."
  },
  {
    id: 64,
    name: "Book Creator",
    vendor: "Red Jumper",
    website: "https://bookcreator.com",
    toolType: "App/Web",
    category: "ELA & Writing",
    subcategory: "Digital Publishing",
    gradeLevels: "K-12",
    subjects: ["ELA"],
    intendedUsers: ["Teachers", "Students"],
    platforms: "Web, iOS, Android",
    pricingModel: "Free 40 books; ~$120/teacher",
    rating: 4,
    parentRelevant: "Low",
    teacherRelevant: "High",
    adminRelevant: "Low",
    description: "Multimedia book-making tool for creating and sharing digital stories and projects."
  },
  {
    id: 65,
    name: "Storybird",
    vendor: "Storybird",
    website: "https://storybird.com",
    toolType: "Website",
    category: "ELA & Writing",
    subcategory: "Creative Writing",
    gradeLevels: "K-8",
    subjects: ["ELA"],
    intendedUsers: ["Teachers", "Students", "Parents"],
    platforms: "Web",
    pricingModel: "~$10/student/yr",
    rating: 4,
    parentRelevant: "Medium",
    teacherRelevant: "High",
    adminRelevant: "Low",
    description: "Art-inspired creative writing platform for illustrated stories and poetry."
  },
  {
    id: 66,
    name: "Grammarly",
    vendor: "Grammarly",
    website: "https://www.grammarly.com",
    toolType: "App/Web",
    category: "ELA & Writing",
    subcategory: "Writing Assistant",
    gradeLevels: "6-12",
    subjects: ["ELA"],
    intendedUsers: ["Students", "Teachers"],
    platforms: "Web, iOS, Android, Chrome ext.",
    pricingModel: "Free; Premium $12/mo",
    rating: 4,
    parentRelevant: "Medium",
    teacherRelevant: "High",
    adminRelevant: "Low",
    description: "AI writing assistant providing grammar, spelling, clarity, and style feedback."
  },
  {
    id: 42,
    name: "Vocabulary.com",
    vendor: "Vocabulary.com",
    website: "https://www.vocabulary.com",
    toolType: "Website/App",
    category: "ELA & Writing",
    subcategory: "Vocabulary",
    gradeLevels: "3-12",
    subjects: ["ELA"],
    intendedUsers: ["Teachers", "Students", "Parents"],
    platforms: "Web, iOS, Android",
    pricingModel: "Free and paid education plans",
    rating: 4,
    parentRelevant: "Medium",
    teacherRelevant: "High",
    adminRelevant: "Low",
    description: "Adaptive vocabulary practice and learning platform."
  },
  {
    id: 45,
    name: "Writable",
    vendor: "Houghton Mifflin Harcourt",
    website: "https://www.writable.com",
    toolType: "Website/App",
    category: "ELA & Writing",
    subcategory: "Writing Instruction",
    gradeLevels: "3-12",
    subjects: ["ELA"],
    intendedUsers: ["Teachers", "Students", "Admins", "Parents"],
    platforms: "Web",
    pricingModel: "School/District license",
    rating: 4,
    parentRelevant: "Low",
    teacherRelevant: "High",
    adminRelevant: "Low",
    description: "Writing assignments, AI-assisted feedback, and assessment platform."
  },

  // ── MATHEMATICS ───────────────────────────────────────────────
  {
    id: 50,
    name: "IXL",
    vendor: "IXL Learning",
    website: "https://www.ixl.com",
    toolType: "Website/App",
    category: "Mathematics",
    subcategory: "Adaptive Practice",
    gradeLevels: "PreK-12",
    subjects: ["Math", "ELA", "Science"],
    intendedUsers: ["Students", "Teachers", "Admins", "Parents"],
    platforms: "Web, iOS, Android",
    pricingModel: "$9.95/mo individual; district pricing",
    rating: 5,
    parentRelevant: "Medium",
    teacherRelevant: "High",
    adminRelevant: "Medium",
    description: "Comprehensive adaptive practice and real-time diagnostics across all subjects."
  },
  {
    id: 48,
    name: "Khan Academy",
    vendor: "Khan Academy",
    website: "https://www.khanacademy.org",
    toolType: "Website/App",
    category: "Mathematics",
    subcategory: "Practice + Lessons",
    gradeLevels: "K-12",
    subjects: ["Math", "Science", "ELA", "Social Studies"],
    intendedUsers: ["Teachers", "Students", "Admins", "Parents"],
    platforms: "Web, iOS, Android",
    pricingModel: "Free",
    rating: 5,
    parentRelevant: "High",
    teacherRelevant: "High",
    adminRelevant: "Medium",
    description: "Free lessons, videos, and practice across all subjects for K-12 and beyond."
  },
  {
    id: 57,
    name: "Prodigy Math",
    vendor: "Prodigy Education",
    website: "https://www.prodigygame.com",
    toolType: "Game/App",
    category: "Mathematics",
    subcategory: "Game-Based Learning",
    gradeLevels: "1-8",
    subjects: ["Math"],
    intendedUsers: ["Students", "Teachers", "Parents"],
    platforms: "Web, iOS, Android",
    pricingModel: "Free; Premium ~$8.99/mo families",
    rating: 4,
    parentRelevant: "High",
    teacherRelevant: "High",
    adminRelevant: "Low",
    description: "Fantasy RPG game where students answer curriculum-aligned math questions to progress."
  },
  {
    id: 53,
    name: "Desmos",
    vendor: "Desmos Studio",
    website: "https://www.desmos.com",
    toolType: "Website/App",
    category: "Mathematics",
    subcategory: "Calculators + Activities",
    gradeLevels: "6-12",
    subjects: ["Math"],
    intendedUsers: ["Students", "Teachers", "Parents"],
    platforms: "Web, iOS, Android",
    pricingModel: "Free",
    rating: 5,
    parentRelevant: "Medium",
    teacherRelevant: "High",
    adminRelevant: "Low",
    description: "Free graphing calculator and interactive math activity builder."
  },
  {
    id: 58,
    name: "ST Math",
    vendor: "MIND Research Institute",
    website: "https://www.stmath.com",
    toolType: "Program",
    category: "Mathematics",
    subcategory: "Visual Math",
    gradeLevels: "K-8",
    subjects: ["Math"],
    intendedUsers: ["Teachers", "Students", "Admins"],
    platforms: "Web, iOS",
    pricingModel: "District licensing",
    rating: 4,
    parentRelevant: "Low",
    teacherRelevant: "High",
    adminRelevant: "High",
    description: "Visual, game-based math program building conceptual understanding through spatial reasoning."
  },
  {
    id: 51,
    name: "DreamBox Math",
    vendor: "DreamBox by Curriculum Associates",
    website: "https://www.dreambox.com",
    toolType: "Program",
    category: "Mathematics",
    subcategory: "Adaptive Math",
    gradeLevels: "K-8",
    subjects: ["Math"],
    intendedUsers: ["Teachers", "Students", "Admins", "Parents"],
    platforms: "Web, iOS, Android",
    pricingModel: "District licensing",
    rating: 4,
    parentRelevant: "Medium",
    teacherRelevant: "High",
    adminRelevant: "Low",
    description: "Adaptive math program with embedded formative assessment for K–8."
  },
  {
    id: 52,
    name: "Zearn Math",
    vendor: "Zearn",
    website: "https://www.zearn.org",
    toolType: "Website",
    category: "Mathematics",
    subcategory: "Core Math",
    gradeLevels: "K-5",
    subjects: ["Math"],
    intendedUsers: ["Students", "Teachers", "Admins"],
    platforms: "Web, Chromebook",
    pricingModel: "Free core; paid reports",
    rating: 4,
    parentRelevant: "High",
    teacherRelevant: "High",
    adminRelevant: "High",
    description: "Visual, teacher-designed digital math lessons aligned to major curriculum standards."
  },
  {
    id: 49,
    name: "Khan Academy Kids",
    vendor: "Khan Academy",
    website: "https://www.khanacademy.org/khan-for-educators/khan-kids-page",
    toolType: "App/Website",
    category: "Mathematics",
    subcategory: "Early Learning App",
    gradeLevels: "PreK-2",
    subjects: ["ELA", "Math", "SEL"],
    intendedUsers: ["Students", "Parents", "Teachers"],
    platforms: "iOS, Android, Web",
    pricingModel: "Free",
    rating: 5,
    parentRelevant: "High",
    teacherRelevant: "High",
    adminRelevant: "Low",
    description: "Free early learning app with reading, math, and SEL activities for young children."
  },
  {
    id: 54,
    name: "Amplify Classroom",
    vendor: "Amplify",
    website: "https://amplify.com/amplify-classroom/",
    toolType: "Website",
    category: "Mathematics",
    subcategory: "Interactive Math Activities",
    gradeLevels: "K-12",
    subjects: ["Math"],
    intendedUsers: ["Teachers", "Students"],
    platforms: "Web",
    pricingModel: "Free and paid depending on product",
    rating: 4,
    parentRelevant: "Low",
    teacherRelevant: "High",
    adminRelevant: "Low",
    description: "Interactive classroom math activities (formerly Desmos Classroom, now part of Amplify)."
  },

  // ── SCIENCE ───────────────────────────────────────────────────
  {
    id: 28,
    name: "Discovery Education",
    vendor: "Discovery Education",
    website: "https://www.discoveryeducation.com",
    toolType: "Website",
    category: "Science",
    subcategory: "Digital Content",
    gradeLevels: "K-12",
    subjects: ["Science", "Social Studies", "Math", "ELA"],
    intendedUsers: ["Teachers", "Students", "Admins"],
    platforms: "Web, iOS, Android",
    pricingModel: "District licensing",
    rating: 5,
    parentRelevant: "Low",
    teacherRelevant: "High",
    adminRelevant: "Low",
    description: "Digital curriculum, virtual field trips, and multimedia instructional resources."
  },
  {
    id: 59,
    name: "PhET Simulations",
    vendor: "University of Colorado Boulder",
    website: "https://phet.colorado.edu",
    toolType: "Website",
    category: "Science",
    subcategory: "Interactive Simulations",
    gradeLevels: "K-12 (best 6-12)",
    subjects: ["Science", "Math"],
    intendedUsers: ["Teachers", "Students"],
    platforms: "Web (HTML5)",
    pricingModel: "Free",
    rating: 5,
    parentRelevant: "Low",
    teacherRelevant: "High",
    adminRelevant: "Low",
    description: "Free interactive science and math simulations for hands-on virtual exploration."
  },
  {
    id: 60,
    name: "Gizmos",
    vendor: "ExploreLearning",
    website: "https://www.explorelearning.com",
    toolType: "Website",
    category: "Science",
    subcategory: "Virtual Labs",
    gradeLevels: "3-12",
    subjects: ["Science", "Math"],
    intendedUsers: ["Teachers", "Students"],
    platforms: "Web",
    pricingModel: "~$440/class/yr",
    rating: 4,
    parentRelevant: "Low",
    teacherRelevant: "High",
    adminRelevant: "Low",
    description: "Standards-aligned online math and science simulations for grades 3–12."
  },
  {
    id: 61,
    name: "Mystery Science",
    vendor: "Mystery Science",
    website: "https://mysteryscience.com",
    toolType: "Website",
    category: "Science",
    subcategory: "Science Lessons",
    gradeLevels: "K-5",
    subjects: ["Science"],
    intendedUsers: ["Teachers", "Students"],
    platforms: "Web",
    pricingModel: "~$129/teacher/yr",
    rating: 5,
    parentRelevant: "Low",
    teacherRelevant: "High",
    adminRelevant: "Low",
    description: "Standards-aligned science video lessons and hands-on activities for elementary grades."
  },
  {
    id: 30,
    name: "CK-12",
    vendor: "CK-12 Foundation",
    website: "https://www.ck12.org",
    toolType: "Website",
    category: "Science",
    subcategory: "Open Texts + Practice",
    gradeLevels: "K-12",
    subjects: ["Math", "Science"],
    intendedUsers: ["Teachers", "Students", "Parents"],
    platforms: "Web, iOS, Android",
    pricingModel: "Free",
    rating: 4,
    parentRelevant: "Low",
    teacherRelevant: "High",
    adminRelevant: "Low",
    description: "Free digital textbooks, simulations, and practice problems for math and science."
  },
  {
    id: 29,
    name: "PBS LearningMedia",
    vendor: "PBS",
    website: "https://www.pbslearningmedia.org",
    toolType: "Website",
    category: "Science",
    subcategory: "Open Resources",
    gradeLevels: "PreK-12",
    subjects: ["Science", "Social Studies", "ELA", "Math"],
    intendedUsers: ["Teachers", "Students", "Parents"],
    platforms: "Web, iOS, Android",
    pricingModel: "Free",
    rating: 4,
    parentRelevant: "Low",
    teacherRelevant: "High",
    adminRelevant: "Low",
    description: "Free standards-aligned videos and lesson resources across all subjects."
  },

  // ── CODING & COMPUTER SCIENCE ─────────────────────────────────
  {
    id: 62,
    name: "Tynker",
    vendor: "Tynker",
    website: "https://www.tynker.com",
    toolType: "Website/App",
    category: "Coding & Computer Science",
    subcategory: "Visual Programming",
    gradeLevels: "K-8",
    subjects: ["Computer Science"],
    intendedUsers: ["Teachers", "Students", "Parents"],
    platforms: "Web, iOS, Android",
    pricingModel: "Free basic; $192/yr family",
    rating: 4,
    parentRelevant: "High",
    teacherRelevant: "High",
    adminRelevant: "Low",
    description: "Coding platform teaching block and text programming through games and creative projects."
  },
  {
    id: 63,
    name: "Code.org",
    vendor: "Code.org",
    website: "https://code.org",
    toolType: "Website",
    category: "Coding & Computer Science",
    subcategory: "CS Curriculum",
    gradeLevels: "K-12",
    subjects: ["Computer Science"],
    intendedUsers: ["Teachers", "Students"],
    platforms: "Web",
    pricingModel: "Free",
    rating: 5,
    parentRelevant: "Medium",
    teacherRelevant: "High",
    adminRelevant: "Low",
    description: "Free K-12 computer science curriculum including the iconic Hour of Code activities."
  },
  {
    id: 83,
    name: "Scratch",
    vendor: "MIT Media Lab",
    website: "https://scratch.mit.edu",
    toolType: "Website/App",
    category: "Coding & Computer Science",
    subcategory: "Block-Based Programming",
    gradeLevels: "K-8 (best 3-8)",
    subjects: ["Computer Science"],
    intendedUsers: ["Teachers", "Students", "Parents"],
    platforms: "Web, iOS",
    pricingModel: "Free",
    rating: 5,
    parentRelevant: "Medium",
    teacherRelevant: "High",
    adminRelevant: "Low",
    description: "Free visual programming language for creating interactive stories, games, and animations."
  },

  // ── SOCIAL STUDIES ────────────────────────────────────────────
  {
    id: 67,
    name: "iCivics",
    vendor: "iCivics",
    website: "https://www.icivics.org",
    toolType: "Website",
    category: "Social Studies",
    subcategory: "Civics Games & Lessons",
    gradeLevels: "4-12",
    subjects: ["Social Studies"],
    intendedUsers: ["Teachers", "Students"],
    platforms: "Web",
    pricingModel: "Free",
    rating: 5,
    parentRelevant: "Low",
    teacherRelevant: "High",
    adminRelevant: "Low",
    description: "Free game-based civics education platform created by Justice Sandra Day O'Connor."
  },
  {
    id: 68,
    name: "Google Earth",
    vendor: "Google",
    website: "https://earth.google.com",
    toolType: "App/Web",
    category: "Social Studies",
    subcategory: "Geography & Exploration",
    gradeLevels: "K-12",
    subjects: ["Social Studies", "Science"],
    intendedUsers: ["Teachers", "Students", "Parents"],
    platforms: "Web, iOS, Android",
    pricingModel: "Free",
    rating: 5,
    parentRelevant: "Medium",
    teacherRelevant: "High",
    adminRelevant: "Low",
    description: "Interactive globe for exploring geography, history, and science through satellite imagery."
  },
  {
    id: 26,
    name: "BrainPOP",
    vendor: "BrainPOP",
    website: "https://www.brainpop.com/discover",
    toolType: "Website/App",
    category: "Social Studies",
    subcategory: "Multimedia Content",
    gradeLevels: "K-8",
    subjects: ["All"],
    intendedUsers: ["Teachers", "Students", "Parents"],
    platforms: "Web, iOS, Android",
    pricingModel: "~$120/teacher/yr",
    rating: 4,
    parentRelevant: "Medium",
    teacherRelevant: "High",
    adminRelevant: "Low",
    description: "Animated standards-aligned learning content for core subjects including Social Studies."
  },
  {
    id: 27,
    name: "BrainPOP Jr.",
    vendor: "BrainPOP",
    website: "https://jr.brainpop.com",
    toolType: "Website/App",
    category: "Social Studies",
    subcategory: "Multimedia Content",
    gradeLevels: "K-3",
    subjects: ["All"],
    intendedUsers: ["Teachers", "Students", "Parents"],
    platforms: "Web, iOS, Android",
    pricingModel: "~$120/teacher/yr",
    rating: 4,
    parentRelevant: "Medium",
    teacherRelevant: "High",
    adminRelevant: "Low",
    description: "Early elementary animated learning resources covering Social Studies and core subjects."
  },

  // ── ASSESSMENT & DATA ─────────────────────────────────────────
  {
    id: 69,
    name: "Kahoot!",
    vendor: "Kahoot!",
    website: "https://kahoot.com",
    toolType: "App/Web",
    category: "Assessment & Data",
    subcategory: "Game-Based Assessment",
    gradeLevels: "K-12",
    subjects: ["All"],
    intendedUsers: ["Teachers", "Students", "Admins"],
    platforms: "Web, iOS, Android",
    pricingModel: "Free; EDU plans from $6/mo",
    rating: 5,
    parentRelevant: "Medium",
    teacherRelevant: "High",
    adminRelevant: "Medium",
    description: "Live and asynchronous quiz games for engagement, review, and formative assessment."
  },
  {
    id: 70,
    name: "Quizlet",
    vendor: "Quizlet",
    website: "https://quizlet.com",
    toolType: "App/Web",
    category: "Assessment & Data",
    subcategory: "Flashcards + Study Tools",
    gradeLevels: "K-12",
    subjects: ["All"],
    intendedUsers: ["Teachers", "Students", "Parents"],
    platforms: "Web, iOS, Android",
    pricingModel: "Free; Teacher ~$35/yr",
    rating: 5,
    parentRelevant: "Medium",
    teacherRelevant: "High",
    adminRelevant: "Low",
    description: "Flashcard and study tool platform for vocabulary, facts, and test preparation."
  },
  {
    id: 71,
    name: "Formative",
    vendor: "Formative",
    website: "https://www.formative.com",
    toolType: "Website",
    category: "Assessment & Data",
    subcategory: "Formative Assessment",
    gradeLevels: "K-12",
    subjects: ["All"],
    intendedUsers: ["Teachers", "Admins"],
    platforms: "Web",
    pricingModel: "Free; Gold ~$12/mo",
    rating: 4,
    parentRelevant: "Low",
    teacherRelevant: "High",
    adminRelevant: "High",
    description: "Real-time formative assessment tool for assigning, monitoring, and responding to student work."
  },
  {
    id: 72,
    name: "Nearpod",
    vendor: "Nearpod (Renaissance)",
    website: "https://nearpod.com",
    toolType: "App/Web",
    category: "Assessment & Data",
    subcategory: "Interactive Lessons",
    gradeLevels: "K-12",
    subjects: ["All"],
    intendedUsers: ["Teachers", "Students", "Admins"],
    platforms: "Web, iOS, Android",
    pricingModel: "Free; School/district pricing",
    rating: 5,
    parentRelevant: "Low",
    teacherRelevant: "High",
    adminRelevant: "Medium",
    description: "Interactive presentation platform with embedded assessments and virtual reality field trips."
  },
  {
    id: 73,
    name: "Edulastic",
    vendor: "Edulastic (GoGuardian)",
    website: "https://edulastic.com",
    toolType: "Website",
    category: "Assessment & Data",
    subcategory: "Standards-Based Assessment",
    gradeLevels: "K-12",
    subjects: ["All"],
    intendedUsers: ["Teachers", "Students", "Admins"],
    platforms: "Web",
    pricingModel: "Free; Premium ~$10/student",
    rating: 4,
    parentRelevant: "Low",
    teacherRelevant: "High",
    adminRelevant: "High",
    description: "Standards-aligned assessment creation and reporting for teachers and district leaders."
  },
  {
    id: 74,
    name: "Pear Deck",
    vendor: "Pear Deck (GoGuardian)",
    website: "https://www.peardeck.com",
    toolType: "Website/Add-on",
    category: "Assessment & Data",
    subcategory: "Interactive Presentations",
    gradeLevels: "K-12",
    subjects: ["All"],
    intendedUsers: ["Teachers", "Students"],
    platforms: "Google Slides / PowerPoint add-on",
    pricingModel: "Free; Premium ~$150/teacher",
    rating: 4,
    parentRelevant: "Low",
    teacherRelevant: "High",
    adminRelevant: "Low",
    description: "Add-on that turns Google Slides and PowerPoint into interactive student-response lessons."
  },
  {
    id: 75,
    name: "Socrative",
    vendor: "Socrative (Showbie)",
    website: "https://www.socrative.com",
    toolType: "Website/App",
    category: "Assessment & Data",
    subcategory: "Quizzes & Exit Tickets",
    gradeLevels: "K-12",
    subjects: ["All"],
    intendedUsers: ["Teachers", "Students"],
    platforms: "Web, iOS, Android",
    pricingModel: "Free; PRO ~$59.99/yr",
    rating: 4,
    parentRelevant: "Low",
    teacherRelevant: "High",
    adminRelevant: "Low",
    description: "Quick quiz, exit ticket, and polling platform for instant classroom feedback."
  },
  {
    id: 31,
    name: "i-Ready",
    vendor: "Curriculum Associates",
    website: "https://www.curriculumassociates.com/programs/i-ready",
    toolType: "Program",
    category: "Assessment & Data",
    subcategory: "Diagnostic + Instruction",
    gradeLevels: "K-8",
    subjects: ["Math", "ELA"],
    intendedUsers: ["Teachers", "Students", "Admins", "Parents"],
    platforms: "Web, iOS",
    pricingModel: "School/District license",
    rating: 4,
    parentRelevant: "Medium",
    teacherRelevant: "High",
    adminRelevant: "High",
    description: "Diagnostic assessment and personalized instruction for math and reading, K–8."
  },
  {
    id: 32,
    name: "Renaissance Star Assessments",
    vendor: "Renaissance",
    website: "https://www.renaissance.com",
    toolType: "Website",
    category: "Assessment & Data",
    subcategory: "Universal Screening",
    gradeLevels: "K-12",
    subjects: ["Math", "Reading"],
    intendedUsers: ["Teachers", "Students", "Admins", "Parents"],
    platforms: "Web",
    pricingModel: "School/District license",
    rating: 4,
    parentRelevant: "Low",
    teacherRelevant: "High",
    adminRelevant: "High",
    description: "Assessment tools for universal screening and progress monitoring."
  },
  {
    id: 34,
    name: "NWEA MAP Growth",
    vendor: "NWEA",
    website: "https://www.nwea.org/map-growth/",
    toolType: "Website",
    category: "Assessment & Data",
    subcategory: "Interim Assessment",
    gradeLevels: "K-12",
    subjects: ["Math", "Reading"],
    intendedUsers: ["Teachers", "Students", "Admins", "Parents"],
    platforms: "Web",
    pricingModel: "School/District license",
    rating: 4,
    parentRelevant: "Low",
    teacherRelevant: "High",
    adminRelevant: "High",
    description: "Adaptive interim assessment measuring student growth in math and reading."
  },
  {
    id: 35,
    name: "DIBELS",
    vendor: "Amplify",
    website: "https://amplify.com/programs/amplify-dibels/",
    toolType: "Program",
    category: "Assessment & Data",
    subcategory: "Early Literacy Screening",
    gradeLevels: "K-8",
    subjects: ["ELA"],
    intendedUsers: ["Teachers", "Admins"],
    platforms: "Web, iOS, Android",
    pricingModel: "School/District license",
    rating: 4,
    parentRelevant: "Low",
    teacherRelevant: "High",
    adminRelevant: "High",
    description: "Literacy screening and progress monitoring for early readers."
  },
  {
    id: 36,
    name: "mCLASS",
    vendor: "Amplify",
    website: "https://amplify.com/programs/amplify-mclass/",
    toolType: "Program",
    category: "Assessment & Data",
    subcategory: "Literacy Assessment",
    gradeLevels: "K-6",
    subjects: ["ELA"],
    intendedUsers: ["Teachers", "Admins"],
    platforms: "Web, iOS, Android",
    pricingModel: "School/District license",
    rating: 4,
    parentRelevant: "Low",
    teacherRelevant: "High",
    adminRelevant: "High",
    description: "Foundational literacy assessment suite for identifying at-risk readers."
  },

  // ── SPECIAL ED & ACCESSIBILITY ────────────────────────────────
  {
    id: 76,
    name: "Boom Cards",
    vendor: "Boom Learning",
    website: "https://wow.boomlearning.com",
    toolType: "Website/App",
    category: "Special Ed & Accessibility",
    subcategory: "Digital Task Cards",
    gradeLevels: "PreK-12",
    subjects: ["All"],
    intendedUsers: ["Teachers", "Students", "Parents"],
    platforms: "Web, iOS, Android",
    pricingModel: "Free basic; ~$12.50/mo teacher",
    rating: 4,
    parentRelevant: "Medium",
    teacherRelevant: "High",
    adminRelevant: "Low",
    description: "Self-grading digital task cards popular for special education and intervention."
  },
  {
    id: 77,
    name: "Learning Ally",
    vendor: "Learning Ally",
    website: "https://learningally.org",
    toolType: "App",
    category: "Special Ed & Accessibility",
    subcategory: "Audiobooks + Reading Support",
    gradeLevels: "K-12",
    subjects: ["ELA"],
    intendedUsers: ["Teachers", "Students", "Parents"],
    platforms: "iOS, Android, Web",
    pricingModel: "~$135/student/yr",
    rating: 5,
    parentRelevant: "High",
    teacherRelevant: "High",
    adminRelevant: "Medium",
    description: "Audiobook and reading support service for students with dyslexia and print disabilities."
  },
  {
    id: 78,
    name: "Boardmaker",
    vendor: "Tobii Dynavox",
    website: "https://www.boardmakeronline.com",
    toolType: "Software/Web",
    category: "Special Ed & Accessibility",
    subcategory: "AAC & Visual Supports",
    gradeLevels: "PreK-12",
    subjects: ["All"],
    intendedUsers: ["Teachers", "Students", "Parents"],
    platforms: "Web, iPad",
    pricingModel: "~$199/yr teacher",
    rating: 4,
    parentRelevant: "Medium",
    teacherRelevant: "High",
    adminRelevant: "Medium",
    description: "Symbol-based communication board creator for students with complex communication needs."
  },
  {
    id: 79,
    name: "Snap&Read",
    vendor: "Don Johnston",
    website: "https://www.snapandread.com",
    toolType: "Chrome Ext/App",
    category: "Special Ed & Accessibility",
    subcategory: "Reading Support",
    gradeLevels: "K-12",
    subjects: ["All"],
    intendedUsers: ["Teachers", "Students"],
    platforms: "Chrome, iOS",
    pricingModel: "~$5/student/yr",
    rating: 4,
    parentRelevant: "Medium",
    teacherRelevant: "High",
    adminRelevant: "Medium",
    description: "Text-to-speech extension that reads and simplifies digital text for struggling readers."
  },
  {
    id: 80,
    name: "Read&Write",
    vendor: "Texthelp",
    website: "https://www.texthelp.com/products/read-and-write-education/",
    toolType: "Software/App",
    category: "Special Ed & Accessibility",
    subcategory: "Literacy Toolbar",
    gradeLevels: "K-12",
    subjects: ["All"],
    intendedUsers: ["Teachers", "Students"],
    platforms: "Web, Windows, Mac, iOS",
    pricingModel: "~$8/student/yr",
    rating: 5,
    parentRelevant: "Medium",
    teacherRelevant: "High",
    adminRelevant: "Medium",
    description: "Literacy toolbar providing text-to-speech, word prediction, and reading support."
  },

  // ── CREATIVITY & MEDIA ────────────────────────────────────────
  {
    id: 81,
    name: "Canva for Education",
    vendor: "Canva",
    website: "https://www.canva.com/education/",
    toolType: "Website/App",
    category: "Creativity & Media",
    subcategory: "Design & Presentations",
    gradeLevels: "K-12",
    subjects: ["All"],
    intendedUsers: ["Teachers", "Students"],
    platforms: "Web, iOS, Android",
    pricingModel: "Free for K-12",
    rating: 5,
    parentRelevant: "Low",
    teacherRelevant: "High",
    adminRelevant: "Low",
    description: "Drag-and-drop design platform for creating presentations, posters, videos, and more."
  },
  {
    id: 82,
    name: "Adobe Express",
    vendor: "Adobe",
    website: "https://www.adobe.com/express/",
    toolType: "Website/App",
    category: "Creativity & Media",
    subcategory: "Creative Design",
    gradeLevels: "K-12",
    subjects: ["All"],
    intendedUsers: ["Teachers", "Students"],
    platforms: "Web, iOS, Android",
    pricingModel: "Free for K-12",
    rating: 4,
    parentRelevant: "Low",
    teacherRelevant: "High",
    adminRelevant: "Low",
    description: "Creative tool for making social graphics, short videos, and web pages in education."
  },
  {
    id: 84,
    name: "Flip (Flipgrid)",
    vendor: "Microsoft",
    website: "https://info.flip.com",
    toolType: "App/Web",
    category: "Creativity & Media",
    subcategory: "Video Discussion",
    gradeLevels: "K-12",
    subjects: ["All"],
    intendedUsers: ["Teachers", "Students"],
    platforms: "Web, iOS, Android",
    pricingModel: "Free (Microsoft)",
    rating: 5,
    parentRelevant: "Medium",
    teacherRelevant: "High",
    adminRelevant: "Low",
    description: "Video-based discussion platform for student voice and community building."
  },
  {
    id: 85,
    name: "WeVideo",
    vendor: "WeVideo",
    website: "https://www.wevideo.com",
    toolType: "Website/App",
    category: "Creativity & Media",
    subcategory: "Video Editing",
    gradeLevels: "K-12",
    subjects: ["All"],
    intendedUsers: ["Teachers", "Students"],
    platforms: "Web, iOS, Android",
    pricingModel: "~$4.99/mo; school pricing",
    rating: 4,
    parentRelevant: "Low",
    teacherRelevant: "High",
    adminRelevant: "Low",
    description: "Cloud-based collaborative video creation and editing platform for student projects."
  },
  {
    id: 86,
    name: "Padlet",
    vendor: "Padlet",
    website: "https://padlet.com",
    toolType: "Website/App",
    category: "Creativity & Media",
    subcategory: "Digital Collaboration Board",
    gradeLevels: "K-12",
    subjects: ["All"],
    intendedUsers: ["Teachers", "Students"],
    platforms: "Web, iOS, Android",
    pricingModel: "Free 3 boards; ~$13.99/mo teacher",
    rating: 5,
    parentRelevant: "Low",
    teacherRelevant: "High",
    adminRelevant: "Low",
    description: "Virtual bulletin board for collaborative posting of notes, images, links, and multimedia."
  },

  // ── SOCIAL EMOTIONAL LEARNING ─────────────────────────────────
  {
    id: 87,
    name: "Second Step",
    vendor: "Committee for Children",
    website: "https://www.secondstep.org",
    toolType: "Program",
    category: "Social Emotional Learning",
    subcategory: "SEL Curriculum",
    gradeLevels: "PreK-8",
    subjects: ["SEL"],
    intendedUsers: ["Teachers", "Admins", "Parents"],
    platforms: "Web, in-person kit",
    pricingModel: "District licensing",
    rating: 5,
    parentRelevant: "High",
    teacherRelevant: "High",
    adminRelevant: "High",
    description: "Research-based SEL curriculum covering empathy, emotion management, and problem-solving."
  },
  {
    id: 88,
    name: "MindUP",
    vendor: "Pear Health Labs",
    website: "https://mindup.org",
    toolType: "Program",
    category: "Social Emotional Learning",
    subcategory: "Mindfulness & SEL",
    gradeLevels: "K-8",
    subjects: ["SEL"],
    intendedUsers: ["Teachers", "Admins", "Parents"],
    platforms: "Web, in-person",
    pricingModel: "School/district licensing",
    rating: 4,
    parentRelevant: "Medium",
    teacherRelevant: "High",
    adminRelevant: "High",
    description: "Mindfulness-based SEL program supporting student focus, resilience, and emotional regulation."
  },
  {
    id: 89,
    name: "Panorama Education",
    vendor: "Panorama Education",
    website: "https://www.panoramaed.com",
    toolType: "Platform",
    category: "Social Emotional Learning",
    subcategory: "SEL Data & Surveys",
    gradeLevels: "K-12",
    subjects: ["SEL"],
    intendedUsers: ["Admins", "Teachers"],
    platforms: "Web",
    pricingModel: "District licensing",
    rating: 4,
    parentRelevant: "Low",
    teacherRelevant: "Medium",
    adminRelevant: "High",
    description: "Data platform for measuring student SEL, school climate, and family engagement."
  },
  {
    id: 90,
    name: "Mood Meter",
    vendor: "Yale Center for Emotional Intelligence",
    website: "https://moodmeterapp.com",
    toolType: "App",
    category: "Social Emotional Learning",
    subcategory: "Emotion Tracking",
    gradeLevels: "K-12",
    subjects: ["SEL"],
    intendedUsers: ["Teachers", "Students", "Parents"],
    platforms: "iOS, Android",
    pricingModel: "~$0.99; school licensing",
    rating: 4,
    parentRelevant: "High",
    teacherRelevant: "High",
    adminRelevant: "Medium",
    description: "App based on Yale's RULER approach to help students identify and regulate emotions."
  },
  {
    id: 91,
    name: "Sanford Harmony",
    vendor: "Sanford Education",
    website: "https://www.sanfordharmony.org",
    toolType: "Program",
    category: "Social Emotional Learning",
    subcategory: "Social Skills Curriculum",
    gradeLevels: "PreK-6",
    subjects: ["SEL"],
    intendedUsers: ["Teachers", "Admins"],
    platforms: "Web, physical kits",
    pricingModel: "Free core program",
    rating: 4,
    parentRelevant: "Medium",
    teacherRelevant: "High",
    adminRelevant: "Medium",
    description: "Evidence-based social skills program focused on student connection and inclusion."
  }
];

/**
 * Returns tools relevant to a given audience, sorted High → Medium → Low.
 * @param {"Teachers"|"Parents"|"Admins"} audience
 * @returns {Array}
 */
function getToolsForAudience(audience) {
  const relevanceKey = {
    Teachers: "teacherRelevant",
    Parents:  "parentRelevant",
    Admins:   "adminRelevant"
  }[audience];

  const order = { High: 0, Medium: 1, Low: 2 };

  return EDTECH_TOOLS
    .filter(t => order[t[relevanceKey]] <= 1) // High or Medium only
    .sort((a, b) => order[a[relevanceKey]] - order[b[relevanceKey]]);
}

/**
 * Filters a tool list by a search query across all relevant text fields.
 * @param {Array}  tools
 * @param {string} query
 * @returns {Array}
 */
function filterTools(tools, query) {
  if (!query || !query.trim()) return tools;
  const q = query.toLowerCase();
  return tools.filter(t =>
    t.name.toLowerCase().includes(q) ||
    t.vendor.toLowerCase().includes(q) ||
    t.category.toLowerCase().includes(q) ||
    t.subcategory.toLowerCase().includes(q) ||
    t.toolType.toLowerCase().includes(q) ||
    t.gradeLevels.toLowerCase().includes(q) ||
    t.platforms.toLowerCase().includes(q) ||
    t.subjects.some(s => s.toLowerCase().includes(q)) ||
    t.description.toLowerCase().includes(q) ||
    t.pricingModel.toLowerCase().includes(q)
  );
}
